### ISSUE TITLE
准备入坑的小白求指教

### ISSUE THREAD

**Issue by tlerbao** [December1900/Hackintosh-10400-B460M-MORTAR-RX570#1]
> 实在等不及iMac跟新配置了，双十一准备先入坑黑果，自己写了下面配置以及问题求教。

### 拟定配置

CPU：I5 10400								
主板：MSI B460M Mortar												1939元/套
显卡：蓝宝石RX 590 GME 8G D5									1599元
内存：金士顿(Kingston) DDR4 2666 16GB(8G×2)		499元
硬盘：WD Blue SN550 1TB												789元
电源：酷冷至尊 650W GX650											469元
机箱：预算500左右待定													500元
蓝牙：BCM94360CD														256元
散热：利民 FS140																259元

Q1：MSI B460M Mortar	这主板直接可以插显卡和无线网卡吧，不用转接吧？
Q2：有没有必要必须上ATX主板和机箱？
Q3：10400有没有搭配的比较完美黑果的EFI的ATX主板型号推荐？
Q4：机箱有高颜值推荐吗？无需侧透和各种RGB
Q5：我以后可能使用有线网络，那么装的BCM94360网卡就是为蓝牙而生的是吧？可以混用是吧？
Q6：显卡是RX590还是5500XT？
Q7：以上所有配置请尽情吐槽，我不是土豪，能帮我省钱就太感谢了

**Comment by December1900** [comment]
A1：直插就行了不用。
A2：这一套散热我觉得MATX完全够了，ATX便携性和空间性相对就差了些。
A3：Github搜一下应该是有对应的EFI。
A4：这个因人而异。
A5：94360CD是为了WIFI和蓝牙互不干扰，你要是只用板载网卡，蓝牙用个接收器应该也是行的。
A6：这个没疑问肯定5500XT，新架构散热更好加上GDDR6，不过你这个价格盈通萌宠5600XT开车价到过1799不急可以等等。
A7：1. 内存这个价格可以上酷兽之类的32G了，反正B460内存频率锁了2666没差。
        2. 电源这套配置650W吃不满，可以适当降低预算。
        3. 10400散热用G3压足够了，机箱内有风道就行，FPU单烤降点电压50多度。

**Comment by tlerbao** [comment]
太详细了，先感谢一下。

昨晚才开始看，不是很懂，
Q1、请问如果不装94360CD无线网卡，损失哪些白果功能？
Q2、主用有线网络上网+蓝牙接收器是不是也能实现几乎接近完美白果？
Q3、听说我这个价格的内存能买别的牌子的16x2了，速度一样吗？

**Comment by December1900** [comment]
A1 & A2：应该没有Airdrop/Handoff/Airplay 等功能，如果不需要的话没区别。
A3：不超频不折腾这点延迟和速度差别远不如大容量来的实在。

**Comment by tlerbao** [comment]
@December1900 像您说的 有线网络+蓝牙接收器 可不可以实现Airdrop/Handoff/Airplay功能？

**Comment by December1900** [comment]
> @December1900 像您说的 有线网络+蓝牙接收器 可不可以实现Airdrop/Handoff/Airplay功能？

不可以Airdrop正常工作得需要Wifi，所以需要无线网卡板载是不行的

**Comment by tlerbao** [comment]
这里我不太明白，比如电视的投屏 电视用有线，手机用无线 一样可以投屏 因为在一个子网内就可以。

不知道 我黑果电脑用有线网络 能不能airdrop，或者说我也装一个94360蓝牙无线网卡，但是我还是插网线上网，不知道这些功能都能用不？

这里给我弄的有点蒙圈。

**Comment by December1900** [comment]
Airdrop使用得要Wifi模块，这是**硬件支持**，只用板载有线是不能使用的。

应该是可以的，你拿到手可以试一试，但是也有问题，你要只用有线，不开Wifi那Airdrop还是用不了。

**Comment by tlerbao** [comment]
@December1900 我现在有点理解了，我即使插网线上网，也必须让我的设备从硬件上支持wifi(我可能当前并不是链接wifi上网，但必须保证它开启)，才能用那些功能，
