### ISSUE TITLE
以太网无法联网

### ISSUE THREAD

**Issue by 384782946** [December1900/Hackintosh-10400-B460M-MORTAR-RX570#10]
我的配置是迫击炮b460m+10400+rx480,基本没啥问题，就是以太网无法联网，在github上搜了别的efi后，替换了网卡驱动，就好了，希望有空可以再维护一下，顺便更新一下oc版本，我是小白，不会整

**Comment by December1900** [comment]
会的，年后会修复一些内容更新EFI，然后更新到Big Sur。
