### ISSUE TITLE
睡眠状态显卡风扇还在转，这个问题有办法吗？

### ISSUE THREAD

**Issue by chenronglin** [December1900/Hackintosh-10400-B460M-MORTAR-RX570#2]
这个EFI堪称接近完美！👍

只是睡眠状态显卡风扇还在转，这个问题有办法吗？

**Comment by December1900** [comment]
这个我不太清楚因为我使用的都是正常的，可能是（纯属个人推断：
1. BIOS相关设置没到位或者你的显卡需要打patch
2. 重置SMC看看
3. Win下更新一下显卡驱动，如果不是蓝宝石的显卡把VBIOS刷成蓝宝石的看看

**Comment by chenronglin** [comment]
搞定了，是BIOS设置的问题。erp ready 开关打开
