### ISSUE TITLE
关于 ACPI SSDT-PMC 的必要性

### ISSUE THREAD

**Issue by Owisky** [December1900/Hackintosh-10400-B460M-MORTAR-RX570#3]
根据 dortania 的教程：
Fixing NVRAM (SSDT-PMC）, This SSDT is required for all "true" 300 series motherboards(Z370 is excluded), it specifically brings back NVRAM support and requires very little configuration for the end user.

10th gen motherboards do not need this SSDT, NVRAM's native on these platforms.

应该是不必要的，我同时对比了五个 MSI B460m 的 EFI，其他人也没用过。

**Comment by December1900** [comment]
是的在最新OpenCore对Comet Lake支持中已经不需要这个文件了，因为我定制的比较早是按照Coffee Lake教程来的，对于你提到的问题，最近我时间有限，后续会更新一波EFI
