### ISSUE TITLE
屏幕亮度无法调节

### ISSUE THREAD

**Issue by v03413** [December1900/Hackintosh-10400-B460M-MORTAR-RX570#9]
大佬你好，我的机器和你基本一样；只是我的显卡是rx480，装上之后基本一切正常，但是在却发现屏幕亮度无法调节，设置里面没有亮度条；不知道是不是ACPI没有配置 SSDT-PNLF.aml 的原因，新人刚玩黑果，期待解决，谢谢你的分享~

**Comment by December1900** [comment]
大佬不至于，我看了下我的设置里面也没有亮度调节的选项，屏幕亮度的调节会在笔记本上多一些，台式一般直接用屏幕按钮调节就好了，并且显示器也是需要支持DDC/IC功能，如果你的显示器支持然后下载一个调节亮度的app也是一样的。

PNLF应该是Clover的相关配置文件，不是OpenCore的所以并没有这个文件。

**Comment by v03413** [comment]
对的，你说的没问题；第一次上手黑果MAC，没啥经验；不过这个外接显示器最后我是用了 MonitorControl 这个成功解决了，能够通过快捷键调节。
